name: alpha-beta-crown
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch
    - torchvision
    - onnx
    - onnx2pytorch
    - pyyaml
    - numpy
